config/routes.rb
Rails.application.routes.draw do

  root 'accounts#index'

  get "login", to: 'sessions#new', as: 'login'
  get "logout", to: 'sessions#destroy', as: 'logout'

  resources :users  
  resources :sessions, :except => [:index]  
  resources :journals, :only => [:new, :create]

  resources :accounts do
    resources :journals, :except => [:new, :create]
    collection { post :import }
    collection { get :download }
  end

end

app/models/journal.rb
class Journal < ActiveRecord::Base

  belongs_to :account

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    @account = Account.find(params[:account_id])
    @journals = @account.journals
  end

# GET /journals/0
# GET /journals/0.json
  def list
    @journals = Journal.all
  end


  # GET /journals/1
  # GET /journals/1.json
  def show
    @account = Account.find(params[:account_id])
  end

  # GET /journals/new
  def new
    @journal = Journal.new
    @accounts = Account.all
  end

  # GET /journals/1/edit
  def edit
    @accounts = Account.all
    @account = Account.find(params[:account_id])
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        flash[:notice] = 'Roz-Namcho Entry was successfully created in ' + @journal.account.account_name + "'s Account."
        format.html { redirect_to action: "new" }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        flash[:notice] = 'Roz-Namcho Entry was successfully updated in ' + @journal.account.account_name + "'s Account."
        format.html { redirect_to action: "index" }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @account = Account.find(params[:account_id])
    @journal.destroy
    respond_to do |format|
      flash[:notice] = 'Roz-Namcho Entry was successfully deleted from ' + @journal.account.account_name + "'s Account."
      format.html { redirect_to account_journals_path(@account) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:journal_date, :account_id, :journal_amount, :journal_entry_type, :journal_entry_description)
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :journal_date, 'Date' %><br>
    <%= f.date_select :journal_date %>
  </div>
  <div class="field">
    <%= f.label :account_id, 'Account' %><br>
    <%= collection_select(:journal, :account_id, @accounts, :id, :account_name, {:prompt => true}) %>
  </div>
  <div class="field">
    <%= f.label :journal_amount, 'Amount' %><br>
    <%= f.number_field :journal_amount %>
  </div>
  <div class="field">
    <%= f.label :journal_entry_type, 'Jamaa ~ Khatay' %><br>
    <%= f.select :journal_entry_type, [['Jamaa','Jamaa'],['Khatay','Khatay']] %>
  </div>
  <div class="field">
    <%= f.label :journal_entry_description, 'Description' %><br>
    <%= f.text_area :journal_entry_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/_updateForm.html.erb
<%= form_for([@account, @journal]) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :journal_date, 'Date' %><br>
    <%= f.date_select :journal_date %>
  </div>
  <div class="field">
    <%= f.label :account_id, 'Account' %><br>
    <%= collection_select(:journal, :account_id, @accounts, :id, :account_name, {:prompt => true}) %>
  </div>
  <div class="field">
    <%= f.label :journal_amount, 'Amount' %><br>
    <%= f.number_field :journal_amount %>
  </div>
  <div class="field">
    <%= f.label :journal_entry_type, 'Jamaa ~ Khatay' %><br>
    <%= f.select :journal_entry_type, [['Jamaa','Jamaa'],['Khatay','Khatay']] %>
  </div>
  <div class="field">
    <%= f.label :journal_entry_description, 'Description' %><br>
    <%= f.text_area :journal_entry_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing journal</h1>

<%= render 'updateForm' %>

<%= link_to 'Show', account_journal_path(@account, @journal) %> |
<%= link_to 'Back', account_journals_path(@account) %>

app/views/journals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing <%= @account.account_name + "'s " %> Journal</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Jamaa</th>
      <th>Khatay</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journals.each do |journal| %>
      <tr>
        <td><%= journal.journal_date %></td>
        <% if journal.journal_entry_type == "Jamaa" %>
          <td><%= number_to_currency(journal.journal_amount, unit: "Rs. ") %></td>
          <td></td>
        <% else %>
          <td></td>
          <td><%= number_to_currency(journal.journal_amount, unit: "Rs. ") %></td>
        <% end %>
        <td><%= journal.journal_entry_description %></td>
        <td><%= link_to 'Show', account_journal_path(@account, journal) %></td>
        <td><%= link_to 'Edit', edit_account_journal_path(@account, journal) %></td>
        <td><%= link_to 'Destroy', [@account, journal], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journal Entry', new_journal_path %>

app/views/journals/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Roz-Namcho</h1>

<%= render 'form' %>

<%= link_to 'Back to Accounts', accounts_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @journal.journal_date %>
</p>

<p>
  <strong>Account:</strong>
  <%= @journal.account.account_name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@journal.journal_amount, unit: "Rs: ") %>
</p>

<p>
  <strong>Jamaa ~ Khatay:</strong>
  <%= @journal.journal_entry_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @journal.journal_entry_description %>
</p>

<%= link_to 'Edit', edit_account_journal_path(@account, @journal) %> |
<%= link_to 'Back', account_journals_path(@account) %>