config/routes.rb
Rails.application.routes.draw do

  root 'accounts#index'

  get "login", to: 'sessions#new', as: 'login'
  get "logout", to: 'sessions#destroy', as: 'logout'

  resources :users  
  resources :sessions, :except => [:index]  
  resources :journals, :only => [:new, :create]

  resources :accounts do
    resources :journals, :except => [:new, :create]
    collection { post :import }
    collection { get :download }
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :journals

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
		    Account.create! row.to_hash
		end
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authorize
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  def import
    Account.import(params[:file])
    flash[:notice] = "Accounts imported."
    redirect_to root_url, notice: "Accounts imported."
  end

  def download
    send_file 'public/sample_import.csv'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_name, :account_number, :account_email, :account_balance, :account_details)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_name, 'Name' %><br>
    <%= f.text_field :account_name %>
  </div>
  <div class="field">
    <%= f.label :account_number, 'Contact Number' %><br>
    <%= f.number_field :account_number %>
  </div>
  <div class="field">
    <%= f.label :account_email, 'Email' %><br>
    <%= f.text_field :account_email %>
  </div>
  <div class="field">
    <%= f.label :account_balance, 'Opening Balance' %><br>
    <%= f.number_field :account_balance %>
  </div>
  <div class="field">
    <%= f.label :account_details, 'Details' %><br>
    <%= f.text_area :account_details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Email</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.account_name %></td>
        <td><%= number_to_phone(account.account_number, area_code: true)  %></td>
        <td><%= account.account_email %></td>
        <td><%= account.account_details %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Ledger', account_journals_url(account) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>
<%= link_to 'New Journal Entry', new_journal_path %>

<h2>Import Accounts</h2>

<%= form_tag import_accounts_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<%= link_to 'Sample Import File', download_accounts_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.account_name %>
</p>

<p>
  <strong>Number:</strong>
  <%= number_to_phone(@account.account_number, area_code: true) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.account_email %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.account_balance %>
</p>

<p>
  <strong>Details:</strong>
  <%= @account.account_details %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>